const PATHS = {
  START: '/start',
  REPAIR: '/repair',
  RESEARCH: '/research',
  RESEARCH_RESULTS: '/research-results',
  ROCKETS: '/rockets',
  ROCKET_RESULTS: '/rocket-results',
  PURCHASE: '/purchase',
  INCOME: '/income',
  LEND_LEASE: '/lend-lease',
  PLAN_ATTACKS: '/plan-attacks',
  FLAK: '/flak',
  STRATEGIC_BOMB: '/strategic-bomb',
  RESOLVE_COMBAT: '/resolve-combat',
  RETREAT: '/retreat',
  COMBAT_ROLLS: '/combat-rolls',
  SELECT_CASUALTIES: '/select-casualties',
  LAND_PLANES: '/land-planes',
  PLAN_MOVEMENT: '/plan-movement',
  RUSSIAN_WINTER: '/russian-winter',
  PLACE_UNITS: '/place-units',
  ORDER_UNITS: '/order-units',
  CONFIRM_FINISH: '/confirm-finish'
}
export default PATHS
